# This is a basic workflow to help you get started with Actions

name: Assignment-add

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
     firstNum:
       description : 'enter first number:'
       rquirement: true
      
     secondNum:
       description : 'enter second number:'
       rquirement: true
    
env:
  firstNum: ${{github.event.inputs.firstNum}}
  secondNum: ${{github.event.inputs.secondnum}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
         python-version: 3.9
      
      # Runs a single command using the runners shell
      - name: Run python script for addition
        run: 
          python addition.py $firstNum $secondNum

      # Runs a set of commands using the runners shell
      